#!/usr/bin/env python3
"""Generate root maps, consumer adapters, and Claude pointer-skills.

Repository-internal contributor tooling. Not a consumer installer.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = ROOT / "adapters" / "manifest.json"
REQUIRED_TOOLS = ("claude", "codex", "grok")
GENERATED_HEADER = "<!-- generated by scripts/gen-adapters.py; do not edit -->\n"


def load_manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text())


def validate_manifest(m: dict) -> list[str]:
    errors: list[str] = []
    tools = tuple(m.get("tools") or ())
    if tools != REQUIRED_TOOLS:
        errors.append(f"tools must be exactly {list(REQUIRED_TOOLS)}, got {list(tools)}")
    for key in (
        "instruction_authority",
        "implementation_convention",
        "bootstrap",
        "hard_items",
        "always_ask",
        "routes",
        "skills",
        "suite",
        "consumer",
    ):
        if key not in m:
            errors.append(f"missing manifest key: {key}")
    for route in m.get("routes", []) + m.get("suite_only_routes", []):
        rel = route.get("open")
        if not rel or rel.endswith("/"):
            continue
        if not (ROOT / rel).is_file():
            errors.append(f"route target missing: {rel}")
    for skill in m.get("skills", []):
        guide = skill.get("guide")
        if not guide or not (ROOT / guide).is_file():
            errors.append(f"skill {skill.get('id')}: guide missing: {guide}")
    return errors


def route_cell(route: dict, prefix: str) -> str:
    if prefix and route.get("consumer_text"):
        return route["consumer_text"]
    if route.get("text"):
        return route["text"]
    path = route["open"]
    note = route.get("note")
    cell = f"`{prefix}{path}`"
    if note:
        cell += f" ({note})"
    return cell


def routes_table(routes: list[dict], prefix: str = "") -> str:
    lines = ["| Need | Open |", "|---|---|"]
    for route in routes:
        lines.append(f"| {route['need']} | {route_cell(route, prefix)} |")
    return "\n".join(lines)


def ask_sentence(m: dict, suite: bool) -> str:
    items = ", ".join(m["always_ask"])
    extra = ""
    if suite and m.get("always_ask_suite_extra"):
        extra = f" — {m['always_ask_suite_extra']}"
    return f"Still **always ask** for: {items}{extra} — **if you are the root session**."


def render_agents(m: dict, *, suite: bool) -> str:
    cfg = m["suite"] if suite else m["consumer"]
    prefix = "" if suite else "GUIDES_ROOT/"
    routes = list(m["routes"])
    if suite:
        # Suite-only rows sit with the other working-on-the-suite links.
        insert_at = len(routes) - 2
        routes = routes[:insert_at] + list(m.get("suite_only_routes", [])) + routes[insert_at:]
        title = "# AGENTS.md — project map"
        intro = (
            "**This file is a MAP.** Law lives in the LLM Dev Guides at repo root. "
            "Do not invent a parallel style or stack system.\n\n"
            "Canonical shared entry for **Claude Code** (via `CLAUDE.md` `@AGENTS.md`), "
            "**Codex**, and **Grok Build**."
        )
        guides_help = ""
        commands_note = (
            "When editing guides: match `guides/code-style` density "
            "(decision trees, ✓/✗, anti-patterns, when to break). Consult author before "
            "inventing new layers or changing settled protocol / code-style / stack law."
        )
        bans = [
            "No drive-by refactors of unrelated guides",
            "No restating code-style / stack inside adapters",
            "No inventing missing domain rules as if they were suite law",
            "Adapters stay thin maps only",
        ]
        permissionless = (
            "This project is run with **always-approve / full auto / permissions bypassed**. "
            "You may run commands and edit files freely **within protocol scope rules**."
        )
        done = (
            "Follow protocol definition of done. Summarize what changed; note open questions "
            "for author voice review when the text must “sound like me.”"
        )
    else:
        routes = list(m.get("consumer_extra_routes", [])) + routes
        title = "# AGENTS.md — project map"
        intro = (
            "**This file is a MAP.** Law lives in the LLM Dev Guides. "
            "Do not invent a parallel style or stack system.\n\n"
            "Shared entry for **Codex**, **Grok Build**, and **Claude Code** "
            "(Claude loads this file through `CLAUDE.md` `@AGENTS.md`). "
            "Copy this file to the consumer repo root as `AGENTS.md`."
        )
        guides_help = (
            "\nReplace `{{GUIDES_ROOT}}` with the path to the suite "
            "(example: `../LLM-dev-guides` or `docs/llm-dev-guides`).  \n"
            "Inside the suite repo itself, use `.`\n"
        )
        commands_note = (
            "If a cell is unknown, discover from `package.json` / Makefile / README — "
            "do not invent a second toolchain."
        )
        bans = [
            "No drive-by refactors or out-of-scope file edits",
            "No inventing missing domain rules as if they were suite law",
            "No restating code-style / stack in this file — link and open the guide",
            "Tests must not be worse; run lint/typecheck when the project has them",
        ]
        permissionless = (
            "This project is run with **always-approve / full auto / permissionless** "
            "tool execution (see `adapters/*/NOTES.md` for the tool flag). "
            "You may run commands and edit files freely **within protocol scope rules**."
        )
        done = (
            "Follow **protocol definition of done** and post-task check. "
            "Summarize what changed and what you deliberately did not touch."
        )

    cmd_rows = [
        f"| Test | {cfg['test']} |",
        f"| Lint | {cfg['lint']} |",
        f"| Typecheck / build | {cfg['build']} |",
    ]
    if not suite:
        cmd_rows.append(f"| Dev (if needed) | {cfg['dev']} |")
    else:
        cmd_rows.append(f"| Preview guides | {cfg['preview']} |")

    hard = m["hard_items"]
    parts = [
        GENERATED_HEADER,
        title,
        "",
        intro,
        "",
        "## GUIDES_ROOT",
        "",
        "```text",
        f"GUIDES_ROOT={cfg['guides_root']}",
        "```",
        guides_help,
        routes_table(routes, prefix),
        "",
        m["bootstrap"],
        "",
        f"**Instruction authority:** {m['instruction_authority']}.",
        "",
        f"**Implementation convention:** {m['implementation_convention']}.",
        "",
        "---",
        "",
        "## Permissionless mode",
        "",
        permissionless,
        "",
        ask_sentence(m, suite),
        "",
        "**If you are a subagent:** you **cannot** ask the human. Escalate always-ask "
        "items to your **parent** (options + recommendation). Parent decides or "
        f"escalates; hard items ({hard}) go human via root. See protocol.",
        "",
        "Permissionless ≠ autonomous product or architecture decisions.",
        "",
        "---",
        "",
        "## Exact commands",
        "",
    ]
    if not suite:
        parts.append("<!-- Fill per consumer project. Examples only — replace. -->")
        parts.append("")
    parts.extend(
        [
            "| Action | Command |",
            "|---|---|",
            *cmd_rows,
            "",
            commands_note,
            "",
            "---",
            "",
            "## Hard bans",
            "",
            *[f"- {b}" for b in bans],
            "",
            "## Done",
            "",
            done,
            "",
        ]
    )
    return "\n".join(parts)


def render_claude(m: dict, *, suite: bool) -> str:
    if suite:
        body = """# Claude Code — mechanics

Claude-specific wiring only. Shared law is in `AGENTS.md` (imported above). Do not restate protocol / code-style / stack here.

## Permissionless

This project is run with **permissions bypassed** (no interactive tool-approval prompts). Permissionless ≠ autonomous product or architecture decisions.

## Claude-only notes

- **Pointer-skills:** `adapters/claude/skills/` — one thin skill per domain that tells Claude to read the right guide. No law lives in the skills.
- **Hooks:** `adapters/claude/hooks/` — SessionStart injects STATUS, PreToolUse blocks edits on the protected base branch, Stop runs the Test command. Hooks enforce local gates; they do not replace protocol definition of done.
- Optional path-scoped rules: `.claude/rules/*.md` — **project facts only**, not a fork of code-style / stack.
- Prefer MCP / project tools already configured; do not add new global tooling without asking.
"""
    else:
        body = """# Claude Code — mechanics

Install **both** this file and `AGENTS.md`. Shared law is imported above. Do not restate protocol / code-style / stack here.

## Permissionless

This project is run with **permissions bypassed** (no interactive tool-approval prompts). You may run commands and edit files freely **within protocol scope rules**. Permissionless ≠ autonomous product or architecture decisions.

## Claude-only notes

- **Pointer-skills:** install `GUIDES_ROOT/adapters/claude/skills/` into `.claude/skills/` — one thin skill per domain that tells Claude to read the right guide. No law lives in the skills.
- **Hooks:** install `GUIDES_ROOT/adapters/claude/hooks/` per its README — SessionStart injects STATUS, PreToolUse blocks edits on the protected base branch, Stop runs the Test command. Hooks enforce local gates; they do not replace protocol definition of done.
- Optional path-scoped rules: `.claude/rules/*.md` — **project facts only**, not a fork of code-style / stack.
- Prefer MCP / project tools already configured; do not add new global tooling without asking.
"""
    return GENERATED_HEADER + "@AGENTS.md\n\n" + body


HEADING_RE = re.compile(r"^##\s+(.*?)\s*$")
SECTION_TAG_RE = re.compile(r"\s*`\[[a-z-]+\]`\s*$")


def guide_sections(guide_rel: str) -> list[tuple[int, int, str]]:
    """Line ranges for every `## ` section, so skills route to sections not files."""
    lines = (ROOT / guide_rel).read_text().splitlines()
    heads = [
        (n, SECTION_TAG_RE.sub("", mt.group(1)))
        for n, line in enumerate(lines, start=1)
        if (mt := HEADING_RE.match(line))
    ]
    return [
        (start, heads[i + 1][0] - 1 if i + 1 < len(heads) else len(lines), title)
        for i, (start, title) in enumerate(heads)
    ]


def render_skill(m: dict, skill: dict) -> str:
    sections = guide_sections(skill["guide"])
    width = max(len(f"{s}-{e}") for s, e, _ in sections)
    rows = "\n".join(f"{s}-{e}".ljust(width) + f"  {title}" for s, e, title in sections)
    return (
        f"---\n"
        f"name: {skill['id']}\n"
        f"description: \"{skill['description']}\"\n"
        f"---\n"
        f"\n"
        f"Law: `GUIDES_ROOT/{skill['guide']}` (`GUIDES_ROOT` from `AGENTS.md`).\n"
        f"Read **only** the ranges you need: `Read(path, offset=START, limit=END-START+1)`.\n"
        f"Examples live in `REFERENCE.md` beside it.\n"
        f"\n"
        f"{rows}\n"
        f"\n"
        f"Guide and local convention outrank this skill; never paraphrase law from memory.\n"
        f"Protocol still applies: `GUIDES_ROOT/guides/protocol/RULES.md`.\n"
    )


def expected_files(m: dict) -> dict[str, str]:
    suite_agents = render_agents(m, suite=True)
    consumer_agents = render_agents(m, suite=False)
    out = {
        "AGENTS.md": suite_agents,
        "CLAUDE.md": render_claude(m, suite=True),
        "adapters/claude/AGENTS.md": consumer_agents,
        "adapters/claude/CLAUDE.md": render_claude(m, suite=False),
        "adapters/codex/AGENTS.md": consumer_agents,
        "adapters/grok/AGENTS.md": consumer_agents,
    }
    for skill in m["skills"]:
        out[f"adapters/claude/skills/{skill['id']}/SKILL.md"] = render_skill(m, skill)
    return out


def check(m: dict) -> int:
    errors = validate_manifest(m)
    expected = expected_files(m)
    for rel, want in expected.items():
        path = ROOT / rel
        if not path.is_file():
            errors.append(f"{rel}: missing (run python3 scripts/gen-adapters.py --write)")
            continue
        got = path.read_text()
        if got != want:
            errors.append(f"{rel}: drifted from generator output")
    if errors:
        for e in errors:
            print(f"FAIL: {e}", file=sys.stderr)
        print("gen-adapters --check: FAILED", file=sys.stderr)
        return 1
    print(f"gen-adapters --check: OK ({len(expected)} generated files)")
    return 0


def write(m: dict) -> int:
    errors = validate_manifest(m)
    if errors:
        for e in errors:
            print(f"FAIL: {e}", file=sys.stderr)
        return 1
    expected = expected_files(m)
    for rel, want in expected.items():
        path = ROOT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(want)
        print(rel)
    print(f"gen-adapters --write: OK ({len(expected)} files)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="fail if generated files drifted")
    mode.add_argument("--write", action="store_true", help="regenerate files in this repo")
    args = parser.parse_args()
    if not MANIFEST_PATH.is_file():
        print(f"FAIL: manifest missing: {MANIFEST_PATH}", file=sys.stderr)
        return 1
    m = load_manifest()
    return check(m) if args.check else write(m)


if __name__ == "__main__":
    sys.exit(main())
